layout_spectrum: 0.006177576588429879
typography_spectrum: 0.20244920242042974
color:
  lightness: 0.49267472749778835
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  saturation: 0.7837900459362508
  brandStrength: 0.03076700340135779
  rhythmicContrast: 0.7794830157156887
name: Circle Press Design
analytics:
  google: UA-49634017-1
purpose:
  - type: contact
    url: 'mailto:circlepressdesign@gmail.com'
    label: Email Me!
github: true
description: Designing logos and marketing websites since 2015
cta: {}
author:
  name: Kyle Carline
  url: 'http://circlepress.design'
  email: circlepressdesign@gmail.com
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/be969b54-721e-427b-9520-08feb7de2332.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/be969b54-721e-427b-9520-08feb7de2332.jpg
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - name: Logos
    id: eeefc06a-4d66-43c6-9187-fecb16176f53
    type: content
  - name: Websites
    id: 9f3881f4-246d-4723-9517-2e501a17eb47
    type: content
  - name: Videos
    id: 82b63a53-6e43-47bf-9bd7-a647445d36ca
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a574b4bc-9413-4421-8f2f-0341fd3f6909.jpg
content_rating:
  adult: false
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
opengraph: {}
title: Grow Your Brand With Good Marketing & Digital Design
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4630b1b0-6095-4e22-9702-01f1bdd5a305.png
url: 'http://circlepress.design'
