layout_spectrum: 0.33214697265066206
typography_spectrum: 0.3219
color:
  brandColors:
    - '#414640'
    - '#636d6c'
    - '#fffdfd'
    - '#a7bdc0'
    - '#b3798a'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
coverPrefs:
  filter: false
name: Circle Press Design
cta: {}
analytics:
  google: UA-49634017-1
opengraph:
  type: ''
  appId: ''
purpose: []
title: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
