name: Circle Press Design
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e9071ddc-dc92-4d34-9731-be67ede7bfdc.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c046572f-4b44-4eae-b9a5-bceb74b0f084.png
layout_spectrum: 0.7114169979467988
typography_spectrum: 0.3219
cta: {}
analytics:
  google: UA-49634017-1
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#414640'
    - '#636d6c'
    - '#fffdfd'
    - '#a7bdc0'
    - '#b3798a'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
title: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
