name: Circle Press Design
layout_spectrum: 0.3768971
typography_spectrum: 0.3219
cta: {}
analytics:
  google: UA-49634017-1
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#414640'
    - '#636d6c'
    - '#fffdfd'
    - '#a7bdc0'
    - '#b3798a'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
title: ''
author:
  name: Contact Kyle
  url: ''
  email: circlepressdesign@gmail.com
content_rating:
  adult: false
