layout_spectrum: 0.8008660138584673
typography_spectrum: 0.3219
color:
  brandColors:
    - '#414640'
    - '#636d6c'
    - '#fffdfd'
    - '#a7bdc0'
    - '#b3798a'
  brandStrength: 0.4920492907986045
  lightness: 0.6097870925441384
  saturation: 0.5947495384607464
  rhythmicContrast: 0.3627955690026283
coverPrefs:
  filter: false
name: Circle Press Design
favicon: null
title: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-49634017-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: ''
  appId: ''
purpose: []
