typography_spectrum: 0.3219
content_rating:
  adult: false
color:
  brandColors:
    - '#414640'
    - '#636d6c'
    - '#fffdfd'
    - '#a7bdc0'
    - '#b3798a'
  brandStrength: 0.10584510792978108
  lightness: 0.3160746172070503
  saturation: 0.7812548372894526
  rhythmicContrast: 0.02445887541398406
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.7363079758360982
analytics:
  google: UA-49634017-1
author:
  name: Kyle Carline
  url: 'http://circlepress.design'
  email: circlepressdesign@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8ea218f7-a00f-4ca7-84e7-f3dd75bfa222.jpg
name: Circle Press Design
cta: {}
navigation:
  - name: The Logo Quilt
    id: eeefc06a-4d66-43c6-9187-fecb16176f53
    type: content
  - name: Websites
    id: 9f3881f4-246d-4723-9517-2e501a17eb47
    type: content
  - name: Videography
    id: 82b63a53-6e43-47bf-9bd7-a647445d36ca
    type: content
  - name: Contact Me
    id: 83d2eb04-3481-495c-8a9b-666a7cad70a2
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a574b4bc-9413-4421-8f2f-0341fd3f6909.jpg
title: Logo Design // Brand Consulting // Website Managment
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/be969b54-721e-427b-9520-08feb7de2332.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/be969b54-721e-427b-9520-08feb7de2332.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: contact
    url: 'mailto:circlepressdesign@gmail.com'
    label: Email Me!
  - type: contact
    url: 'tel:804-251-0040'
    label: Or Call Me
url: 'http://circlepress.design'
github: true
