name: Circle Press Design
favicon: null
layout_spectrum: 0.2571
typography_spectrum: 0.3219
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-49634017-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#414640'
    - '#636d6c'
    - '#fffdfd'
    - '#a7bdc0'
    - '#b3798a'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
