name: Circle Press Design
analytics:
  twitter: circlepressdesign_twitter
  google: UA-49634017-1
purpose:
  - type: contact
    url: 'mailto:circlepressdesign@gmail.com'
    label: Email Me!
  - type: contact
    url: 'tel:804-251-0040'
    label: Or Call Me
github: true
description: Portfolio of work by Kyle Carline
cta: {}
author:
  name: Kyle Carline
  url: 'http://circlepress.design'
  email: circlepressdesign@gmail.com
color:
  lightness: 0.08657625213763354
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  saturation: 0.7244478700994191
  brandStrength: 0.3691968269345562
  rhythmicContrast: 0.4147856982299449
layout_spectrum: 0.1927683792050264
navigation:
  - id: eeefc06a-4d66-43c6-9187-fecb16176f53
    name: Logos
    type: content
  - id: 9f3881f4-246d-4723-9517-2e501a17eb47
    name: Websites
    type: content
  - id: 82b63a53-6e43-47bf-9bd7-a647445d36ca
    name: Videos
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a574b4bc-9413-4421-8f2f-0341fd3f6909.jpg
content_rating:
  adult: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/be969b54-721e-427b-9520-08feb7de2332.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/be969b54-721e-427b-9520-08feb7de2332.jpg
    metadata:
      author: []
      '@context': 'http://schema.org'
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
typography_spectrum: 0.3290032295084162
opengraph: {}
title: Logos - Marketing - Website Stuff
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4630b1b0-6095-4e22-9702-01f1bdd5a305.png
url: 'http://circlepress.design'
