analytics:
  google: UA-49634017-1
color:
  brandColors:
    - '#414640'
    - '#636d6c'
    - '#fffdfd'
    - '#a7bdc0'
    - '#b3798a'
  brandStrength: 0.5
  lightness: 1
  rhythmicContrast: 0.75
  saturation: 0
cta: {}
layout_spectrum: 0.217905
name: Circle Press Design
opengraph: {}
purpose: []
typography_spectrum: 0.3219
